//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.MeasureItemEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.MeasureItemEventHandler">MeasureItemEventHandler</seealso>
	/// </summary>
	public static partial class MeasureItemEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// measureitemeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this MeasureItemEventHandler measureitemeventhandler, Object sender, MeasureItemEventArgs e, AsyncCallback callback)
		{
			if(measureitemeventhandler == null) throw new ArgumentNullException("measureitemeventhandler");

			return measureitemeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
