//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Common;

namespace PRI.ProductivityExtensions.DbDataReaderExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.Common.DbDataReader">DbDataReader</seealso>
	/// </summary>
	public static partial class DbDataReaderable
	{
		/// <summary>
		/// Extends GetBytes so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// dbdatareader.GetBytes(ordinal, dataOffset, buffer);
		/// </example>
		/// </summary>
		public static Int64 GetBytes(this DbDataReader dbdatareader, Int32 ordinal, Int64 dataOffset, Byte[] buffer)
		{
			if(dbdatareader == null) throw new ArgumentNullException("dbdatareader");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return dbdatareader.GetBytes(ordinal, dataOffset, buffer, 0, buffer.Length);
		}

		/// <summary>
		/// Extends GetChars so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// dbdatareader.GetChars(ordinal, dataOffset, buffer);
		/// </example>
		/// </summary>
		public static Int64 GetChars(this DbDataReader dbdatareader, Int32 ordinal, Int64 dataOffset, Char[] buffer)
		{
			if(dbdatareader == null) throw new ArgumentNullException("dbdatareader");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return dbdatareader.GetChars(ordinal, dataOffset, buffer, 0, buffer.Length);
		}

	}
}
