//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;

namespace PRI.ProductivityExtensions.FileSystemEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.IO.FileSystemEventHandler">FileSystemEventHandler</seealso>
	/// </summary>
	public static partial class FileSystemEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// filesystemeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this FileSystemEventHandler filesystemeventhandler, Object sender, FileSystemEventArgs e, AsyncCallback callback)
		{
			if(filesystemeventhandler == null) throw new ArgumentNullException("filesystemeventhandler");

			return filesystemeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
