#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

namespace PRI.ProductivityExtensions.DoWorkEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ComponentModel.DoWorkEventHandler">DoWorkEventHandler</seealso>
	/// </summary>
	public static partial class DoWorkEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// doworkeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DoWorkEventHandler doworkeventhandler, Object sender, DoWorkEventArgs e, AsyncCallback callback)
		{
			if(doworkeventhandler == null) throw new ArgumentNullException("doworkeventhandler");

			return doworkeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif