#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;

namespace PRI.ProductivityExtensions.OnChangeEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.SqlClient.OnChangeEventHandler">OnChangeEventHandler</seealso>
	/// </summary>
	public static partial class OnChangeEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// onchangeeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this OnChangeEventHandler onchangeeventhandler, Object sender, SqlNotificationEventArgs e, AsyncCallback callback)
		{
			if(onchangeeventhandler == null) throw new ArgumentNullException("onchangeeventhandler");

			return onchangeeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif