#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.WebBrowserProgressChangedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.WebBrowserProgressChangedEventHandler">WebBrowserProgressChangedEventHandler</seealso>
	/// </summary>
	public static partial class WebBrowserProgressChangedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// webbrowserprogresschangedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this WebBrowserProgressChangedEventHandler webbrowserprogresschangedeventhandler, Object sender, WebBrowserProgressChangedEventArgs e, AsyncCallback callback)
		{
			if(webbrowserprogresschangedeventhandler == null) throw new ArgumentNullException("webbrowserprogresschangedeventhandler");

			return webbrowserprogresschangedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif