#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net;

namespace PRI.ProductivityExtensions.FtpWebRequestExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.FtpWebRequest">FtpWebRequest</seealso>
	/// </summary>
	public static partial class FtpWebRequestable
	{
		/// <summary>
		/// Extends BeginGetResponse so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// ftpwebrequest.BeginGetResponse(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginGetResponse(this FtpWebRequest ftpwebrequest, AsyncCallback callback)
		{
			if(ftpwebrequest == null) throw new ArgumentNullException("ftpwebrequest");

			return ftpwebrequest.BeginGetResponse(callback, null);
		}

		/// <summary>
		/// Extends BeginGetRequestStream so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// ftpwebrequest.BeginGetRequestStream(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginGetRequestStream(this FtpWebRequest ftpwebrequest, AsyncCallback callback)
		{
			if(ftpwebrequest == null) throw new ArgumentNullException("ftpwebrequest");

			return ftpwebrequest.BeginGetRequestStream(callback, null);
		}

	}
}
#endif