//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.TreeNodeMouseClickEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.TreeNodeMouseClickEventHandler">TreeNodeMouseClickEventHandler</seealso>
	/// </summary>
	public static partial class TreeNodeMouseClickEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// treenodemouseclickeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this TreeNodeMouseClickEventHandler treenodemouseclickeventhandler, Object sender, TreeNodeMouseClickEventArgs e, AsyncCallback callback)
		{
			if(treenodemouseclickeventhandler == null) throw new ArgumentNullException("treenodemouseclickeventhandler");

			return treenodemouseclickeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
