//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewRowPostPaintEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewRowPostPaintEventHandler">DataGridViewRowPostPaintEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewRowPostPaintEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewrowpostpainteventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewRowPostPaintEventHandler datagridviewrowpostpainteventhandler, Object sender, DataGridViewRowPostPaintEventArgs e, AsyncCallback callback)
		{
			if(datagridviewrowpostpainteventhandler == null) throw new ArgumentNullException("datagridviewrowpostpainteventhandler");

			return datagridviewrowpostpainteventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
