#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.Design;

namespace PRI.ProductivityExtensions.ActiveDesignerEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ComponentModel.Design.ActiveDesignerEventHandler">ActiveDesignerEventHandler</seealso>
	/// </summary>
	public static partial class ActiveDesignerEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// activedesignereventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ActiveDesignerEventHandler activedesignereventhandler, Object sender, ActiveDesignerEventArgs e, AsyncCallback callback)
		{
			if(activedesignereventhandler == null) throw new ArgumentNullException("activedesignereventhandler");

			return activedesignereventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif