#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.OleDb;

namespace PRI.ProductivityExtensions.OleDbInfoMessageEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.OleDb.OleDbInfoMessageEventHandler">OleDbInfoMessageEventHandler</seealso>
	/// </summary>
	public static partial class OleDbInfoMessageEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// oledbinfomessageeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this OleDbInfoMessageEventHandler oledbinfomessageeventhandler, Object sender, OleDbInfoMessageEventArgs e, AsyncCallback callback)
		{
			if(oledbinfomessageeventhandler == null) throw new ArgumentNullException("oledbinfomessageeventhandler");

			return oledbinfomessageeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif