#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO.Pipes;

namespace PRI.ProductivityExtensions.AnonymousPipeClientStreamExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.IO.Pipes.AnonymousPipeClientStream">AnonymousPipeClientStream</seealso>
	/// </summary>
	public static partial class AnonymousPipeClientStreamable
	{
		/// <summary>
		/// Extends BeginRead so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// pipestream.BeginRead(buffer, offset, count, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginRead(this AnonymousPipeClientStream pipestream, Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback)
		{
			if(pipestream == null) throw new ArgumentNullException("pipestream");

			return pipestream.BeginRead(buffer, offset, count, callback, null);
		}

		/// <summary>
		/// Extends BeginRead so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// pipestream.BeginRead(buffer, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginRead(this AnonymousPipeClientStream pipestream, Byte[] buffer, AsyncCallback callback)
		{
			if(pipestream == null) throw new ArgumentNullException("pipestream");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return pipestream.BeginRead(buffer, 0, buffer.Length, callback);
		}

		/// <summary>
		/// Extends BeginWrite so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// pipestream.BeginWrite(buffer, offset, count, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginWrite(this AnonymousPipeClientStream pipestream, Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback)
		{
			if(pipestream == null) throw new ArgumentNullException("pipestream");

			return pipestream.BeginWrite(buffer, offset, count, callback, null);
		}

		/// <summary>
		/// Extends BeginWrite so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// pipestream.BeginWrite(buffer, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginWrite(this AnonymousPipeClientStream pipestream, Byte[] buffer, AsyncCallback callback)
		{
			if(pipestream == null) throw new ArgumentNullException("pipestream");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return pipestream.BeginWrite(buffer, 0, buffer.Length, callback);
		}

	}
}
#endif