#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data;

namespace PRI.ProductivityExtensions.MergeFailedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.MergeFailedEventHandler">MergeFailedEventHandler</seealso>
	/// </summary>
	public static partial class MergeFailedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// mergefailedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this MergeFailedEventHandler mergefailedeventhandler, Object sender, MergeFailedEventArgs e, AsyncCallback callback)
		{
			if(mergefailedeventhandler == null) throw new ArgumentNullException("mergefailedeventhandler");

			return mergefailedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif