#if (NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.BindingCompleteEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.BindingCompleteEventHandler">BindingCompleteEventHandler</seealso>
	/// </summary>
	public static partial class BindingCompleteEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// bindingcompleteeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this BindingCompleteEventHandler bindingcompleteeventhandler, Object sender, BindingCompleteEventArgs e, AsyncCallback callback)
		{
			if(bindingcompleteeventhandler == null) throw new ArgumentNullException("bindingcompleteeventhandler");

			return bindingcompleteeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif