//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.ToolBarButtonClickEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.ToolBarButtonClickEventHandler">ToolBarButtonClickEventHandler</seealso>
	/// </summary>
	public static partial class ToolBarButtonClickEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// toolbarbuttonclickeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ToolBarButtonClickEventHandler toolbarbuttonclickeventhandler, Object sender, ToolBarButtonClickEventArgs e, AsyncCallback callback)
		{
			if(toolbarbuttonclickeventhandler == null) throw new ArgumentNullException("toolbarbuttonclickeventhandler");

			return toolbarbuttonclickeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
