#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.QueryAccessibilityHelpEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.QueryAccessibilityHelpEventHandler">QueryAccessibilityHelpEventHandler</seealso>
	/// </summary>
	public static partial class QueryAccessibilityHelpEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// queryaccessibilityhelpeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this QueryAccessibilityHelpEventHandler queryaccessibilityhelpeventhandler, Object sender, QueryAccessibilityHelpEventArgs e, AsyncCallback callback)
		{
			if(queryaccessibilityhelpeventhandler == null) throw new ArgumentNullException("queryaccessibilityhelpeventhandler");

			return queryaccessibilityhelpeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif