//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Drawing.Design;

namespace PRI.ProductivityExtensions.PropertyValueUIHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Drawing.Design.PropertyValueUIHandler">PropertyValueUIHandler</seealso>
	/// </summary>
	public static partial class PropertyValueUIHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// propertyvalueuihandler.BeginInvoke(context, propDesc, valueUIItemList, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this PropertyValueUIHandler propertyvalueuihandler, System.ComponentModel.ITypeDescriptorContext context, System.ComponentModel.PropertyDescriptor propDesc, System.Collections.ArrayList valueUIItemList, AsyncCallback callback)
		{
			if(propertyvalueuihandler == null) throw new ArgumentNullException("propertyvalueuihandler");

			return propertyvalueuihandler.BeginInvoke(context, propDesc, valueUIItemList, callback, null);
		}

	}
}
