//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

namespace PRI.ProductivityExtensions.IComNativeDescriptorHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ComponentModel.IComNativeDescriptorHandler">IComNativeDescriptorHandler</seealso>
	/// </summary>
	public static partial class IComNativeDescriptorHandlerable
	{
#pragma warning disable CS0618 // 'IComNativeDescriptorHandler' is obsolete: 'This interface has been deprecated. Add a TypeDescriptionProvider to handle type TypeDescriptor.ComObjectType instead.  http://go.microsoft.com/fwlink/?linkid=14202'
		/// <summary>
		/// Extends GetEditor so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// icomnativedescriptorhandler.GetEditor&lt;int&gt;(component);
		/// </example>
		/// </summary>
		public static T GetEditor<T>(this IComNativeDescriptorHandler icomnativedescriptorhandler, Object component)
#pragma warning restore CS0618 // 'IComNativeDescriptorHandler' is obsolete: 'This interface has been deprecated. Add a TypeDescriptionProvider to handle type TypeDescriptor.ComObjectType instead.  http://go.microsoft.com/fwlink/?linkid=14202'
		{
			if(icomnativedescriptorhandler == null) throw new ArgumentNullException("icomnativedescriptorhandler");

			return (T)icomnativedescriptorhandler.GetEditor(component, typeof(T));
		}

	}
}
