#if (NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Drawing.Design;

namespace PRI.ProductivityExtensions.ToolboxItemCreatorCallbackExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Drawing.Design.ToolboxItemCreatorCallback">ToolboxItemCreatorCallback</seealso>
	/// </summary>
	public static partial class ToolboxItemCreatorCallbackable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// toolboxitemcreatorcallback.BeginInvoke(serializedObject, format, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ToolboxItemCreatorCallback toolboxitemcreatorcallback, Object serializedObject, String format, AsyncCallback callback)
		{
			if(toolboxitemcreatorcallback == null) throw new ArgumentNullException("toolboxitemcreatorcallback");

			return toolboxitemcreatorcallback.BeginInvoke(serializedObject, format, callback, null);
		}

	}
}
#endif