//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.ToolStripPanelRenderEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.ToolStripPanelRenderEventHandler">ToolStripPanelRenderEventHandler</seealso>
	/// </summary>
	public static partial class ToolStripPanelRenderEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// toolstrippanelrendereventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ToolStripPanelRenderEventHandler toolstrippanelrendereventhandler, Object sender, ToolStripPanelRenderEventArgs e, AsyncCallback callback)
		{
			if(toolstrippanelrendereventhandler == null) throw new ArgumentNullException("toolstrippanelrendereventhandler");

			return toolstrippanelrendereventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
