//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.RetrieveVirtualItemEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.RetrieveVirtualItemEventHandler">RetrieveVirtualItemEventHandler</seealso>
	/// </summary>
	public static partial class RetrieveVirtualItemEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// retrievevirtualitemeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this RetrieveVirtualItemEventHandler retrievevirtualitemeventhandler, Object sender, RetrieveVirtualItemEventArgs e, AsyncCallback callback)
		{
			if(retrievevirtualitemeventhandler == null) throw new ArgumentNullException("retrievevirtualitemeventhandler");

			return retrievevirtualitemeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
