#if (NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace PRI.ProductivityExtensions.CrossAppDomainDelegateExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.CrossAppDomainDelegate">CrossAppDomainDelegate</seealso>
	/// </summary>
	public static partial class CrossAppDomainDelegateable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// crossappdomaindelegate.BeginInvoke(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this CrossAppDomainDelegate crossappdomaindelegate, AsyncCallback callback)
		{
			if(crossappdomaindelegate == null) throw new ArgumentNullException("crossappdomaindelegate");

			return crossappdomaindelegate.BeginInvoke(callback, null);
		}

	}
}
#endif