//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Controls;

namespace PRI.ProductivityExtensions.SelectionChangedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Controls.SelectionChangedEventHandler">SelectionChangedEventHandler</seealso>
	/// </summary>
	public static partial class SelectionChangedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// selectionchangedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this SelectionChangedEventHandler selectionchangedeventhandler, Object sender, SelectionChangedEventArgs e, AsyncCallback callback)
		{
			if(selectionchangedeventhandler == null) throw new ArgumentNullException("selectionchangedeventhandler");

			return selectionchangedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
