//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Schema;

namespace PRI.ProductivityExtensions.XmlAtomicValueExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Xml.Schema.XmlAtomicValue">XmlAtomicValue</seealso>
	/// </summary>
	public static partial class XmlAtomicValueable
	{
		/// <summary>
		/// Extends ValueAs so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// xmlatomicvalue.ValueAs<int>(nsResolver);
		/// </example>
		/// </summary>
		public static T ValueAs<T>(this XmlAtomicValue xmlatomicvalue, System.Xml.IXmlNamespaceResolver nsResolver)
		{
			if(xmlatomicvalue == null) throw new ArgumentNullException("xmlatomicvalue");

			return (T)xmlatomicvalue.ValueAs(typeof(T), nsResolver);
		}

	}
}
