#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

namespace PRI.ProductivityExtensions.AddingNewEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ComponentModel.AddingNewEventHandler">AddingNewEventHandler</seealso>
	/// </summary>
	public static partial class AddingNewEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// addingneweventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this AddingNewEventHandler addingneweventhandler, Object sender, AddingNewEventArgs e, AsyncCallback callback)
		{
			if(addingneweventhandler == null) throw new ArgumentNullException("addingneweventhandler");

			return addingneweventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif