//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;

namespace PRI.ProductivityExtensions.SqlRowUpdatedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.SqlClient.SqlRowUpdatedEventHandler">SqlRowUpdatedEventHandler</seealso>
	/// </summary>
	public static partial class SqlRowUpdatedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// sqlrowupdatedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this SqlRowUpdatedEventHandler sqlrowupdatedeventhandler, Object sender, SqlRowUpdatedEventArgs e, AsyncCallback callback)
		{
			if(sqlrowupdatedeventhandler == null) throw new ArgumentNullException("sqlrowupdatedeventhandler");

			return sqlrowupdatedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
