#if (NETSTANDARD2_0 || NETSTANDARD1_6 || NETSTANDARD1_5 || NETSTANDARD1_4 || NETSTANDARD1_3 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace PRI.ProductivityExtensions.ConsoleCancelEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ConsoleCancelEventHandler">ConsoleCancelEventHandler</seealso>
	/// </summary>
	public static partial class ConsoleCancelEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// consolecanceleventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ConsoleCancelEventHandler consolecanceleventhandler, Object sender, ConsoleCancelEventArgs e, AsyncCallback callback)
		{
			if(consolecanceleventhandler == null) throw new ArgumentNullException("consolecanceleventhandler");

			return consolecanceleventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif