//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Drawing.Printing;

namespace PRI.ProductivityExtensions.QueryPageSettingsEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Drawing.Printing.QueryPageSettingsEventHandler">QueryPageSettingsEventHandler</seealso>
	/// </summary>
	public static partial class QueryPageSettingsEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// querypagesettingseventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this QueryPageSettingsEventHandler querypagesettingseventhandler, Object sender, QueryPageSettingsEventArgs e, AsyncCallback callback)
		{
			if(querypagesettingseventhandler == null) throw new ArgumentNullException("querypagesettingseventhandler");

			return querypagesettingseventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
