//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Sockets;

namespace PRI.ProductivityExtensions.SocketAsyncEventArgsExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.Sockets.SocketAsyncEventArgs">SocketAsyncEventArgs</seealso>
	/// </summary>
	public static partial class SocketAsyncEventArgsable
	{
		/// <summary>
		/// Extends SetBuffer so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// socketasynceventargs.SetBuffer(buffer);
		/// </example>
		/// </summary>
		public static void SetBuffer(this SocketAsyncEventArgs socketasynceventargs, Byte[] buffer)
		{
			if(socketasynceventargs == null) throw new ArgumentNullException("socketasynceventargs");

			if(buffer == null) throw new ArgumentNullException("buffer");

			socketasynceventargs.SetBuffer(buffer, 0, buffer.Length);
		}

	}
}
