#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net;

namespace PRI.ProductivityExtensions.HttpListenerRequestExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.HttpListenerRequest">HttpListenerRequest</seealso>
	/// </summary>
	public static partial class HttpListenerRequestable
	{
		/// <summary>
		/// Extends BeginGetClientCertificate so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// httplistenerrequest.BeginGetClientCertificate(requestCallback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginGetClientCertificate(this HttpListenerRequest httplistenerrequest, AsyncCallback requestCallback)
		{
			if(httplistenerrequest == null) throw new ArgumentNullException("httplistenerrequest");

			return httplistenerrequest.BeginGetClientCertificate(requestCallback, null);
		}

	}
}
#endif