//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.InteropServices;

namespace PRI.ProductivityExtensions.ObjectCreationDelegateExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Runtime.InteropServices.ObjectCreationDelegate">ObjectCreationDelegate</seealso>
	/// </summary>
	public static partial class ObjectCreationDelegateable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// objectcreationdelegate.BeginInvoke(aggregator, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ObjectCreationDelegate objectcreationdelegate, IntPtr aggregator, AsyncCallback callback)
		{
			if(objectcreationdelegate == null) throw new ArgumentNullException("objectcreationdelegate");

			return objectcreationdelegate.BeginInvoke(aggregator, callback, null);
		}

	}
}
