#if (NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.Win32;

namespace PRI.ProductivityExtensions.SessionEndingEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="Microsoft.Win32.SessionEndingEventHandler">SessionEndingEventHandler</seealso>
	/// </summary>
	public static partial class SessionEndingEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// sessionendingeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this SessionEndingEventHandler sessionendingeventhandler, Object sender, SessionEndingEventArgs e, AsyncCallback callback)
		{
			if(sessionendingeventhandler == null) throw new ArgumentNullException("sessionendingeventhandler");

			return sessionendingeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif