#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;

namespace PRI.ProductivityExtensions.RenamedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.IO.RenamedEventHandler">RenamedEventHandler</seealso>
	/// </summary>
	public static partial class RenamedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// renamedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this RenamedEventHandler renamedeventhandler, Object sender, RenamedEventArgs e, AsyncCallback callback)
		{
			if(renamedeventhandler == null) throw new ArgumentNullException("renamedeventhandler");

			return renamedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif