#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Threading;

namespace PRI.ProductivityExtensions.ContextCallbackExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Threading.ContextCallback">ContextCallback</seealso>
	/// </summary>
	public static partial class ContextCallbackable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// contextcallback.BeginInvoke(state, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ContextCallback contextcallback, Object state, AsyncCallback callback)
		{
			if(contextcallback == null) throw new ArgumentNullException("contextcallback");

			return contextcallback.BeginInvoke(state, callback, null);
		}

	}
}
#endif