//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Configuration;

namespace PRI.ProductivityExtensions.SettingsLoadedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Configuration.SettingsLoadedEventHandler">SettingsLoadedEventHandler</seealso>
	/// </summary>
	public static partial class SettingsLoadedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// settingsloadedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this SettingsLoadedEventHandler settingsloadedeventhandler, Object sender, SettingsLoadedEventArgs e, AsyncCallback callback)
		{
			if(settingsloadedeventhandler == null) throw new ArgumentNullException("settingsloadedeventhandler");

			return settingsloadedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
