//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.TreeNodeMouseHoverEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.TreeNodeMouseHoverEventHandler">TreeNodeMouseHoverEventHandler</seealso>
	/// </summary>
	public static partial class TreeNodeMouseHoverEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// treenodemousehovereventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this TreeNodeMouseHoverEventHandler treenodemousehovereventhandler, Object sender, TreeNodeMouseHoverEventArgs e, AsyncCallback callback)
		{
			if(treenodemousehovereventhandler == null) throw new ArgumentNullException("treenodemousehovereventhandler");

			return treenodemousehovereventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
