//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DrawListViewSubItemEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DrawListViewSubItemEventHandler">DrawListViewSubItemEventHandler</seealso>
	/// </summary>
	public static partial class DrawListViewSubItemEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// drawlistviewsubitemeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DrawListViewSubItemEventHandler drawlistviewsubitemeventhandler, Object sender, DrawListViewSubItemEventArgs e, AsyncCallback callback)
		{
			if(drawlistviewsubitemeventhandler == null) throw new ArgumentNullException("drawlistviewsubitemeventhandler");

			return drawlistviewsubitemeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
