//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

namespace PRI.ProductivityExtensions.ModuleResolveEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Reflection.ModuleResolveEventHandler">ModuleResolveEventHandler</seealso>
	/// </summary>
	public static partial class ModuleResolveEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// moduleresolveeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ModuleResolveEventHandler moduleresolveeventhandler, Object sender, ResolveEventArgs e, AsyncCallback callback)
		{
			if(moduleresolveeventhandler == null) throw new ArgumentNullException("moduleresolveeventhandler");

			return moduleresolveeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
