#if (NET40 || NET45)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Configuration;

namespace PRI.ProductivityExtensions.SettingsSavingEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Configuration.SettingsSavingEventHandler">SettingsSavingEventHandler</seealso>
	/// </summary>
	public static partial class SettingsSavingEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// settingssavingeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this SettingsSavingEventHandler settingssavingeventhandler, Object sender, System.ComponentModel.CancelEventArgs e, AsyncCallback callback)
		{
			if(settingssavingeventhandler == null) throw new ArgumentNullException("settingssavingeventhandler");

			return settingssavingeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif