//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO.Pipes;

namespace PRI.ProductivityExtensions.PipeStreamImpersonationWorkerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.IO.Pipes.PipeStreamImpersonationWorker">PipeStreamImpersonationWorker</seealso>
	/// </summary>
	public static partial class PipeStreamImpersonationWorkerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// pipestreamimpersonationworker.BeginInvoke(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this PipeStreamImpersonationWorker pipestreamimpersonationworker, AsyncCallback callback)
		{
			if(pipestreamimpersonationworker == null) throw new ArgumentNullException("pipestreamimpersonationworker");

			return pipestreamimpersonationworker.BeginInvoke(callback, null);
		}

	}
}
