//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewCellMouseEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewCellMouseEventHandler">DataGridViewCellMouseEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewCellMouseEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewcellmouseeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewCellMouseEventHandler datagridviewcellmouseeventhandler, Object sender, DataGridViewCellMouseEventArgs e, AsyncCallback callback)
		{
			if(datagridviewcellmouseeventhandler == null) throw new ArgumentNullException("datagridviewcellmouseeventhandler");

			return datagridviewcellmouseeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
