#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.ToolStripDropDownClosingEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.ToolStripDropDownClosingEventHandler">ToolStripDropDownClosingEventHandler</seealso>
	/// </summary>
	public static partial class ToolStripDropDownClosingEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// toolstripdropdownclosingeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ToolStripDropDownClosingEventHandler toolstripdropdownclosingeventhandler, Object sender, ToolStripDropDownClosingEventArgs e, AsyncCallback callback)
		{
			if(toolstripdropdownclosingeventhandler == null) throw new ArgumentNullException("toolstripdropdownclosingeventhandler");

			return toolstripdropdownclosingeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif