#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Schema;

namespace PRI.ProductivityExtensions.ValidationEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Xml.Schema.ValidationEventHandler">ValidationEventHandler</seealso>
	/// </summary>
	public static partial class ValidationEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// validationeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ValidationEventHandler validationeventhandler, Object sender, ValidationEventArgs e, AsyncCallback callback)
		{
			if(validationeventhandler == null) throw new ArgumentNullException("validationeventhandler");

			return validationeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif