//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace PRI.ProductivityExtensions.ListExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Collections.Generic.List&lt;T&gt;">List&lt;T&gt;</seealso>
	/// </summary>
	public static partial class Listable
	{
		/// <summary>
		/// Extends CopyTo&lt;T&gt; so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// list.CopyTo&lt;T&gt;(index, array);
		/// </example>
		/// </summary>
		public static void CopyTo<T>(this List<T> list, Int32 index, T[] array)
		{
			if(list == null) throw new ArgumentNullException("list");

			if(array == null) throw new ArgumentNullException("array");

			list.CopyTo(index, array, 0, array.Length);
		}

	}
}
