#if (NETSTANDARD2_0 || NETSTANDARD1_6 || NETSTANDARD1_5 || NETSTANDARD1_4 || NETSTANDARD1_3 || NETSTANDARD1_2 || NETSTANDARD1_1 || NETSTANDARD1_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.IO;

namespace PRI.ProductivityExtensions.MemoryStreamExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.IO.MemoryStream">MemoryStream</seealso>
	/// </summary>
	public static partial class MemoryStreamable
	{
#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
		/// <summary>
		/// Extends BeginRead so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// stream.BeginRead(buffer, offset, count, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginRead(this MemoryStream stream, Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback)
		{
			if(stream == null) throw new ArgumentNullException("stream");

			return stream.BeginRead(buffer, offset, count, callback, null);
		}

		/// <summary>
		/// Extends BeginRead so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// stream.BeginRead(buffer, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginRead(this MemoryStream stream, Byte[] buffer, AsyncCallback callback)
		{
			if(stream == null) throw new ArgumentNullException("stream");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return stream.BeginRead(buffer, 0, buffer.Length, callback);
		}

		/// <summary>
		/// Extends BeginWrite so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// stream.BeginWrite(buffer, offset, count, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginWrite(this MemoryStream stream, Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback)
		{
			if(stream == null) throw new ArgumentNullException("stream");

			return stream.BeginWrite(buffer, offset, count, callback, null);
		}

		/// <summary>
		/// Extends BeginWrite so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// stream.BeginWrite(buffer, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginWrite(this MemoryStream stream, Byte[] buffer, AsyncCallback callback)
		{
			if(stream == null) throw new ArgumentNullException("stream");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return stream.BeginWrite(buffer, 0, buffer.Length, callback);
		}
#endif
	}
}
#endif