#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Timers;

namespace PRI.ProductivityExtensions.ElapsedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Timers.ElapsedEventHandler">ElapsedEventHandler</seealso>
	/// </summary>
	public static partial class ElapsedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// elapsedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ElapsedEventHandler elapsedeventhandler, Object sender, ElapsedEventArgs e, AsyncCallback callback)
		{
			if(elapsedeventhandler == null) throw new ArgumentNullException("elapsedeventhandler");

			return elapsedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif