//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Text;

namespace PRI.ProductivityExtensions.StringBuilderExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Text.StringBuilder">StringBuilder</seealso>
	/// </summary>
	public static partial class StringBuilderable
	{
		/// <summary>
		/// Extends CopyTo so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// stringbuilder.CopyTo(sourceIndex, destination);
		/// </example>
		/// </summary>
		public static void CopyTo(this StringBuilder stringbuilder, Int32 sourceIndex, Char[] destination)
		{
			if(stringbuilder == null) throw new ArgumentNullException("stringbuilder");

			if(destination == null) throw new ArgumentNullException("destination");

			stringbuilder.CopyTo(sourceIndex, destination, 0, destination.Length);
		}

	}
}
