//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Input;

namespace PRI.ProductivityExtensions.TextCompositionEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Input.TextCompositionEventHandler">TextCompositionEventHandler</seealso>
	/// </summary>
	public static partial class TextCompositionEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// textcompositioneventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this TextCompositionEventHandler textcompositioneventhandler, Object sender, TextCompositionEventArgs e, AsyncCallback callback)
		{
			if(textcompositioneventhandler == null) throw new ArgumentNullException("textcompositioneventhandler");

			return textcompositioneventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
