//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewCellValueEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewCellValueEventHandler">DataGridViewCellValueEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewCellValueEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewcellvalueeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewCellValueEventHandler datagridviewcellvalueeventhandler, Object sender, DataGridViewCellValueEventArgs e, AsyncCallback callback)
		{
			if(datagridviewcellvalueeventhandler == null) throw new ArgumentNullException("datagridviewcellvalueeventhandler");

			return datagridviewcellvalueeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
