#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.UICuesEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.UICuesEventHandler">UICuesEventHandler</seealso>
	/// </summary>
	public static partial class UICuesEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// uicueseventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this UICuesEventHandler uicueseventhandler, Object sender, UICuesEventArgs e, AsyncCallback callback)
		{
			if(uicueseventhandler == null) throw new ArgumentNullException("uicueseventhandler");

			return uicueseventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif