//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Controls.Primitives;

namespace PRI.ProductivityExtensions.ItemsChangedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Controls.Primitives.ItemsChangedEventHandler">ItemsChangedEventHandler</seealso>
	/// </summary>
	public static partial class ItemsChangedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// itemschangedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ItemsChangedEventHandler itemschangedeventhandler, Object sender, ItemsChangedEventArgs e, AsyncCallback callback)
		{
			if(itemschangedeventhandler == null) throw new ArgumentNullException("itemschangedeventhandler");

			return itemschangedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
