//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.Design.Serialization;

namespace PRI.ProductivityExtensions.IDesignerSerializationManagerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ComponentModel.Design.Serialization.IDesignerSerializationManager">IDesignerSerializationManager</seealso>
	/// </summary>
	public static partial class IDesignerSerializationManagerable
	{
		/// <summary>
		/// Extends CreateInstance so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// idesignerserializationmanager.CreateInstance&lt;int&gt;(arguments, name, addToContainer);
		/// </example>
		/// </summary>
		public static T CreateInstance<T>(this IDesignerSerializationManager idesignerserializationmanager, System.Collections.ICollection arguments, String name, Boolean addToContainer)
		{
			if(idesignerserializationmanager == null) throw new ArgumentNullException("idesignerserializationmanager");

			return (T)idesignerserializationmanager.CreateInstance(typeof(T), arguments, name, addToContainer);
		}

	}
}
