//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Navigation;

namespace PRI.ProductivityExtensions.NavigationStoppedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Navigation.NavigationStoppedEventHandler">NavigationStoppedEventHandler</seealso>
	/// </summary>
	public static partial class NavigationStoppedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// navigationstoppedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this NavigationStoppedEventHandler navigationstoppedeventhandler, Object sender, NavigationEventArgs e, AsyncCallback callback)
		{
			if(navigationstoppedeventhandler == null) throw new ArgumentNullException("navigationstoppedeventhandler");

			return navigationstoppedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
