#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Security;

namespace PRI.ProductivityExtensions.LocalCertificateSelectionCallbackExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.Security.LocalCertificateSelectionCallback">LocalCertificateSelectionCallback</seealso>
	/// </summary>
	public static partial class LocalCertificateSelectionCallbackable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// localcertificateselectioncallback.BeginInvoke(sender, targetHost, localCertificates, remoteCertificate, acceptableIssuers, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this LocalCertificateSelectionCallback localcertificateselectioncallback, Object sender, String targetHost, System.Security.Cryptography.X509Certificates.X509CertificateCollection localCertificates, System.Security.Cryptography.X509Certificates.X509Certificate remoteCertificate, String[] acceptableIssuers, AsyncCallback callback)
		{
			if(localcertificateselectioncallback == null) throw new ArgumentNullException("localcertificateselectioncallback");

			return localcertificateselectioncallback.BeginInvoke(sender, targetHost, localCertificates, remoteCertificate, acceptableIssuers, callback, null);
		}

	}
}
#endif