#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.OleDb;

namespace PRI.ProductivityExtensions.OleDbRowUpdatingEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.OleDb.OleDbRowUpdatingEventHandler">OleDbRowUpdatingEventHandler</seealso>
	/// </summary>
	public static partial class OleDbRowUpdatingEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// oledbrowupdatingeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this OleDbRowUpdatingEventHandler oledbrowupdatingeventhandler, Object sender, OleDbRowUpdatingEventArgs e, AsyncCallback callback)
		{
			if(oledbrowupdatingeventhandler == null) throw new ArgumentNullException("oledbrowupdatingeventhandler");

			return oledbrowupdatingeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif