#if (NETSTANDARD1_6 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.SqlClient;

namespace PRI.ProductivityExtensions.SqlInfoMessageEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.SqlClient.SqlInfoMessageEventHandler">SqlInfoMessageEventHandler</seealso>
	/// </summary>
	public static partial class SqlInfoMessageEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// sqlinfomessageeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this SqlInfoMessageEventHandler sqlinfomessageeventhandler, Object sender, SqlInfoMessageEventArgs e, AsyncCallback callback)
		{
			if(sqlinfomessageeventhandler == null) throw new ArgumentNullException("sqlinfomessageeventhandler");

			return sqlinfomessageeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif