//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.ColumnWidthChangedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.ColumnWidthChangedEventHandler">ColumnWidthChangedEventHandler</seealso>
	/// </summary>
	public static partial class ColumnWidthChangedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// columnwidthchangedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ColumnWidthChangedEventHandler columnwidthchangedeventhandler, Object sender, ColumnWidthChangedEventArgs e, AsyncCallback callback)
		{
			if(columnwidthchangedeventhandler == null) throw new ArgumentNullException("columnwidthchangedeventhandler");

			return columnwidthchangedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
