#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.KeyEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.KeyEventHandler">KeyEventHandler</seealso>
	/// </summary>
	public static partial class KeyEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// keyeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this KeyEventHandler keyeventhandler, Object sender, KeyEventArgs e, AsyncCallback callback)
		{
			if(keyeventhandler == null) throw new ArgumentNullException("keyeventhandler");

			return keyeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif