//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewRowHeightInfoPushedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewRowHeightInfoPushedEventHandler">DataGridViewRowHeightInfoPushedEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewRowHeightInfoPushedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewrowheightinfopushedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewRowHeightInfoPushedEventHandler datagridviewrowheightinfopushedeventhandler, Object sender, DataGridViewRowHeightInfoPushedEventArgs e, AsyncCallback callback)
		{
			if(datagridviewrowheightinfopushedeventhandler == null) throw new ArgumentNullException("datagridviewrowheightinfopushedeventhandler");

			return datagridviewrowheightinfopushedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
