//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net;

namespace PRI.ProductivityExtensions.UploadProgressChangedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.UploadProgressChangedEventHandler">UploadProgressChangedEventHandler</seealso>
	/// </summary>
	public static partial class UploadProgressChangedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// uploadprogresschangedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this UploadProgressChangedEventHandler uploadprogresschangedeventhandler, Object sender, UploadProgressChangedEventArgs e, AsyncCallback callback)
		{
			if(uploadprogresschangedeventhandler == null) throw new ArgumentNullException("uploadprogresschangedeventhandler");

			return uploadprogresschangedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
