//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Schema;

namespace PRI.ProductivityExtensions.XmlValueGetterExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Xml.Schema.XmlValueGetter">XmlValueGetter</seealso>
	/// </summary>
	public static partial class XmlValueGetterable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// xmlvaluegetter.BeginInvoke(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this XmlValueGetter xmlvaluegetter, AsyncCallback callback)
		{
			if(xmlvaluegetter == null) throw new ArgumentNullException("xmlvaluegetter");

			return xmlvaluegetter.BeginInvoke(callback, null);
		}

	}
}
