//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace PRI.ProductivityExtensions.PredicateExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Predicate<T>">Predicate<T></seealso>
	/// </summary>
	public static partial class Predicateable
	{
		/// <summary>
		/// Extends BeginInvoke<T> so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// predicate.BeginInvoke<T>(obj, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke<T>(this Predicate<T> predicate, T obj, AsyncCallback callback)
		{
			if(predicate == null) throw new ArgumentNullException("predicate");

			return predicate.BeginInvoke(obj, callback, null);
		}

	}
}
