//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;

namespace PRI.ProductivityExtensions.RoutedPropertyChangedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.RoutedPropertyChangedEventHandler<T>">RoutedPropertyChangedEventHandler<T></seealso>
	/// </summary>
	public static partial class RoutedPropertyChangedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke<T> so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// routedpropertychangedeventhandler.BeginInvoke<T>(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke<T>(this RoutedPropertyChangedEventHandler<T> routedpropertychangedeventhandler, Object sender, RoutedPropertyChangedEventArgs<T> e, AsyncCallback callback)
		{
			if(routedpropertychangedeventhandler == null) throw new ArgumentNullException("routedpropertychangedeventhandler");

			return routedpropertychangedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
