//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewBindingCompleteEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewBindingCompleteEventHandler">DataGridViewBindingCompleteEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewBindingCompleteEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewbindingcompleteeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewBindingCompleteEventHandler datagridviewbindingcompleteeventhandler, Object sender, DataGridViewBindingCompleteEventArgs e, AsyncCallback callback)
		{
			if(datagridviewbindingcompleteeventhandler == null) throw new ArgumentNullException("datagridviewbindingcompleteeventhandler");

			return datagridviewbindingcompleteeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
