#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.XPath;

namespace PRI.ProductivityExtensions.XPathNavigatorExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Xml.XPath.XPathNavigator">XPathNavigator</seealso>
	/// </summary>
	public static partial class XPathNavigatorable
	{
		/// <summary>
		/// Extends ValueAs so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// xpathnavigator.ValueAs&lt;int&gt;(nsResolver);
		/// </example>
		/// </summary>
		public static T ValueAs<T>(this XPathNavigator xpathnavigator, System.Xml.IXmlNamespaceResolver nsResolver)
		{
			if(xpathnavigator == null) throw new ArgumentNullException("xpathnavigator");

			return (T)xpathnavigator.ValueAs(typeof(T), nsResolver);
		}

	}
}
#endif