//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Input;

namespace PRI.ProductivityExtensions.TouchFrameEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Input.TouchFrameEventHandler">TouchFrameEventHandler</seealso>
	/// </summary>
	public static partial class TouchFrameEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// touchframeeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this TouchFrameEventHandler touchframeeventhandler, Object sender, TouchFrameEventArgs e, AsyncCallback callback)
		{
			if(touchframeeventhandler == null) throw new ArgumentNullException("touchframeeventhandler");

			return touchframeeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
