//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewCellEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewCellEventHandler">DataGridViewCellEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewCellEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewcelleventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewCellEventHandler datagridviewcelleventhandler, Object sender, DataGridViewCellEventArgs e, AsyncCallback callback)
		{
			if(datagridviewcelleventhandler == null) throw new ArgumentNullException("datagridviewcelleventhandler");

			return datagridviewcelleventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
