//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DateBoldEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DateBoldEventHandler">DateBoldEventHandler</seealso>
	/// </summary>
	public static partial class DateBoldEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// dateboldeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DateBoldEventHandler dateboldeventhandler, Object sender, DateBoldEventArgs e, AsyncCallback callback)
		{
			if(dateboldeventhandler == null) throw new ArgumentNullException("dateboldeventhandler");

			return dateboldeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
