//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.PopupEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.PopupEventHandler">PopupEventHandler</seealso>
	/// </summary>
	public static partial class PopupEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// popupeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this PopupEventHandler popupeventhandler, Object sender, PopupEventArgs e, AsyncCallback callback)
		{
			if(popupeventhandler == null) throw new ArgumentNullException("popupeventhandler");

			return popupeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
