//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.TreeViewCancelEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.TreeViewCancelEventHandler">TreeViewCancelEventHandler</seealso>
	/// </summary>
	public static partial class TreeViewCancelEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// treeviewcanceleventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this TreeViewCancelEventHandler treeviewcanceleventhandler, Object sender, TreeViewCancelEventArgs e, AsyncCallback callback)
		{
			if(treeviewcanceleventhandler == null) throw new ArgumentNullException("treeviewcanceleventhandler");

			return treeviewcanceleventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
