#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.NetworkInformation;

namespace PRI.ProductivityExtensions.PingCompletedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.NetworkInformation.PingCompletedEventHandler">PingCompletedEventHandler</seealso>
	/// </summary>
	public static partial class PingCompletedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// pingcompletedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this PingCompletedEventHandler pingcompletedeventhandler, Object sender, PingCompletedEventArgs e, AsyncCallback callback)
		{
			if(pingcompletedeventhandler == null) throw new ArgumentNullException("pingcompletedeventhandler");

			return pingcompletedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif