//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.ToolStripDropDownClosedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.ToolStripDropDownClosedEventHandler">ToolStripDropDownClosedEventHandler</seealso>
	/// </summary>
	public static partial class ToolStripDropDownClosedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// toolstripdropdownclosedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ToolStripDropDownClosedEventHandler toolstripdropdownclosedeventhandler, Object sender, ToolStripDropDownClosedEventArgs e, AsyncCallback callback)
		{
			if(toolstripdropdownclosedeventhandler == null) throw new ArgumentNullException("toolstripdropdownclosedeventhandler");

			return toolstripdropdownclosedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
