//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DragEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DragEventHandler">DragEventHandler</seealso>
	/// </summary>
	public static partial class DragEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// drageventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DragEventHandler drageventhandler, Object sender, DragEventArgs e, AsyncCallback callback)
		{
			if(drageventhandler == null) throw new ArgumentNullException("drageventhandler");

			return drageventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
