//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml;

namespace PRI.ProductivityExtensions.XmlUrlResolverExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Xml.XmlUrlResolver">XmlUrlResolver</seealso>
	/// </summary>
	public static partial class XmlUrlResolverable
	{
		/// <summary>
		/// Extends GetEntity so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// xmlurlresolver.GetEntity<int>(absoluteUri, role);
		/// </example>
		/// </summary>
		public static T GetEntity<T>(this XmlUrlResolver xmlurlresolver, Uri absoluteUri, String role)
		{
			if(xmlurlresolver == null) throw new ArgumentNullException("xmlurlresolver");

			return (T)xmlurlresolver.GetEntity(absoluteUri, role, typeof(T));
		}

	}
}
