//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewRowsAddedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewRowsAddedEventHandler">DataGridViewRowsAddedEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewRowsAddedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewrowsaddedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewRowsAddedEventHandler datagridviewrowsaddedeventhandler, Object sender, DataGridViewRowsAddedEventArgs e, AsyncCallback callback)
		{
			if(datagridviewrowsaddedeventhandler == null) throw new ArgumentNullException("datagridviewrowsaddedeventhandler");

			return datagridviewrowsaddedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
