//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Input;

namespace PRI.ProductivityExtensions.MouseWheelEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Input.MouseWheelEventHandler">MouseWheelEventHandler</seealso>
	/// </summary>
	public static partial class MouseWheelEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// mousewheeleventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this MouseWheelEventHandler mousewheeleventhandler, Object sender, MouseWheelEventArgs e, AsyncCallback callback)
		{
			if(mousewheeleventhandler == null) throw new ArgumentNullException("mousewheeleventhandler");

			return mousewheeleventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
