#if (NETSTANDARD1_6 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using Microsoft.SqlServer.Server;

namespace PRI.ProductivityExtensions.SqlDataRecordExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="Microsoft.SqlServer.Server.SqlDataRecord">SqlDataRecord</seealso>
	/// </summary>
	public static partial class SqlDataRecordable
	{
		/// <summary>
		/// Extends GetBytes so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// sqldatarecord.GetBytes(ordinal, fieldOffset, buffer);
		/// </example>
		/// </summary>
		public static Int64 GetBytes(this SqlDataRecord sqldatarecord, Int32 ordinal, Int64 fieldOffset, Byte[] buffer)
		{
			if(sqldatarecord == null) throw new ArgumentNullException("sqldatarecord");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return sqldatarecord.GetBytes(ordinal, fieldOffset, buffer, 0, buffer.Length);
		}

		/// <summary>
		/// Extends GetChars so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// sqldatarecord.GetChars(ordinal, fieldOffset, buffer);
		/// </example>
		/// </summary>
		public static Int64 GetChars(this SqlDataRecord sqldatarecord, Int32 ordinal, Int64 fieldOffset, Char[] buffer)
		{
			if(sqldatarecord == null) throw new ArgumentNullException("sqldatarecord");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return sqldatarecord.GetChars(ordinal, fieldOffset, buffer, 0, buffer.Length);
		}

		/// <summary>
		/// Extends SetBytes so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// sqldatarecord.SetBytes(ordinal, fieldOffset, buffer);
		/// </example>
		/// </summary>
		public static void SetBytes(this SqlDataRecord sqldatarecord, Int32 ordinal, Int64 fieldOffset, Byte[] buffer)
		{
			if(sqldatarecord == null) throw new ArgumentNullException("sqldatarecord");

			if(buffer == null) throw new ArgumentNullException("buffer");

			sqldatarecord.SetBytes(ordinal, fieldOffset, buffer, 0, buffer.Length);
		}

		/// <summary>
		/// Extends SetChars so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// sqldatarecord.SetChars(ordinal, fieldOffset, buffer);
		/// </example>
		/// </summary>
		public static void SetChars(this SqlDataRecord sqldatarecord, Int32 ordinal, Int64 fieldOffset, Char[] buffer)
		{
			if(sqldatarecord == null) throw new ArgumentNullException("sqldatarecord");

			if(buffer == null) throw new ArgumentNullException("buffer");

			sqldatarecord.SetChars(ordinal, fieldOffset, buffer, 0, buffer.Length);
		}

	}
}
#endif