#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.StatusBarDrawItemEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.StatusBarDrawItemEventHandler">StatusBarDrawItemEventHandler</seealso>
	/// </summary>
	public static partial class StatusBarDrawItemEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// statusbardrawitemeventhandler.BeginInvoke(sender, sbdevent, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this StatusBarDrawItemEventHandler statusbardrawitemeventhandler, Object sender, StatusBarDrawItemEventArgs sbdevent, AsyncCallback callback)
		{
			if(statusbardrawitemeventhandler == null) throw new ArgumentNullException("statusbardrawitemeventhandler");

			return statusbardrawitemeventhandler.BeginInvoke(sender, sbdevent, callback, null);
		}

	}
}
#endif