//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

namespace PRI.ProductivityExtensions.InstanceCreationEditorExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ComponentModel.InstanceCreationEditor">InstanceCreationEditor</seealso>
	/// </summary>
	public static partial class InstanceCreationEditorable
	{
		/// <summary>
		/// Extends CreateInstance so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// instancecreationeditor.CreateInstance<int>(context);
		/// </example>
		/// </summary>
		public static T CreateInstance<T>(this InstanceCreationEditor instancecreationeditor, ITypeDescriptorContext context)
		{
			if(instancecreationeditor == null) throw new ArgumentNullException("instancecreationeditor");

			return (T)instancecreationeditor.CreateInstance(context, typeof(T));
		}

	}
}
