#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net;

namespace PRI.ProductivityExtensions.FileWebRequestExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.FileWebRequest">FileWebRequest</seealso>
	/// </summary>
	public static partial class FileWebRequestable
	{
		/// <summary>
		/// Extends BeginGetResponse so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// filewebrequest.BeginGetResponse(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginGetResponse(this FileWebRequest filewebrequest, AsyncCallback callback)
		{
			if(filewebrequest == null) throw new ArgumentNullException("filewebrequest");

			return filewebrequest.BeginGetResponse(callback, null);
		}

		/// <summary>
		/// Extends BeginGetRequestStream so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// filewebrequest.BeginGetRequestStream(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginGetRequestStream(this FileWebRequest filewebrequest, AsyncCallback callback)
		{
			if(filewebrequest == null) throw new ArgumentNullException("filewebrequest");

			return filewebrequest.BeginGetRequestStream(callback, null);
		}

	}
}
#endif