//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Controls.Primitives;

namespace PRI.ProductivityExtensions.DragStartedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Controls.Primitives.DragStartedEventHandler">DragStartedEventHandler</seealso>
	/// </summary>
	public static partial class DragStartedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// dragstartedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DragStartedEventHandler dragstartedeventhandler, Object sender, DragStartedEventArgs e, AsyncCallback callback)
		{
			if(dragstartedeventhandler == null) throw new ArgumentNullException("dragstartedeventhandler");

			return dragstartedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
