//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Sockets;

namespace PRI.ProductivityExtensions.UdpAnySourceMulticastClientExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.Sockets.UdpAnySourceMulticastClient">UdpAnySourceMulticastClient</seealso>
	/// </summary>
	public static partial class UdpAnySourceMulticastClientable
	{
		/// <summary>
		/// Extends BeginJoinGroup so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// udpanysourcemulticastclient.BeginJoinGroup(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginJoinGroup(this UdpAnySourceMulticastClient udpanysourcemulticastclient, AsyncCallback callback)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			return udpanysourcemulticastclient.BeginJoinGroup(callback, null);
		}

		/// <summary>
		/// Extends BeginReceiveFromGroup so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// udpanysourcemulticastclient.BeginReceiveFromGroup(buffer, callback, state);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginReceiveFromGroup(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, AsyncCallback callback, Object state)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return udpanysourcemulticastclient.BeginReceiveFromGroup(buffer, 0, buffer.Length, callback, state);
		}

		/// <summary>
		/// Extends BeginReceiveFromGroup so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// udpanysourcemulticastclient.BeginReceiveFromGroup(buffer, offset, count, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginReceiveFromGroup(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			return udpanysourcemulticastclient.BeginReceiveFromGroup(buffer, offset, count, callback, null);
		}

		/// <summary>
		/// Extends BeginReceiveFromGroup so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// udpanysourcemulticastclient.BeginReceiveFromGroup(buffer, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginReceiveFromGroup(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, AsyncCallback callback)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return udpanysourcemulticastclient.BeginReceiveFromGroup(buffer, 0, buffer.Length, callback);
		}

		/// <summary>
		/// Extends BeginSendToGroup so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// udpanysourcemulticastclient.BeginSendToGroup(buffer, callback, state);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginSendToGroup(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, AsyncCallback callback, Object state)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return udpanysourcemulticastclient.BeginSendToGroup(buffer, 0, buffer.Length, callback, state);
		}

		/// <summary>
		/// Extends BeginSendToGroup so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// udpanysourcemulticastclient.BeginSendToGroup(buffer, offset, count, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginSendToGroup(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, Int32 offset, Int32 count, AsyncCallback callback)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			return udpanysourcemulticastclient.BeginSendToGroup(buffer, offset, count, callback, null);
		}

		/// <summary>
		/// Extends BeginSendToGroup so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// udpanysourcemulticastclient.BeginSendToGroup(buffer, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginSendToGroup(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, AsyncCallback callback)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return udpanysourcemulticastclient.BeginSendToGroup(buffer, 0, buffer.Length, callback);
		}

		/// <summary>
		/// Extends BeginSendTo so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// udpanysourcemulticastclient.BeginSendTo(buffer, remoteEndPoint, callback, state);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginSendTo(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, System.Net.IPEndPoint remoteEndPoint, AsyncCallback callback, Object state)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return udpanysourcemulticastclient.BeginSendTo(buffer, 0, buffer.Length, remoteEndPoint, callback, state);
		}

		/// <summary>
		/// Extends BeginSendTo so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// udpanysourcemulticastclient.BeginSendTo(buffer, offset, count, remoteEndPoint, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginSendTo(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, Int32 offset, Int32 count, System.Net.IPEndPoint remoteEndPoint, AsyncCallback callback)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			return udpanysourcemulticastclient.BeginSendTo(buffer, offset, count, remoteEndPoint, callback, null);
		}

		/// <summary>
		/// Extends BeginSendTo so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// udpanysourcemulticastclient.BeginSendTo(buffer, remoteEndPoint, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginSendTo(this UdpAnySourceMulticastClient udpanysourcemulticastclient, Byte[] buffer, System.Net.IPEndPoint remoteEndPoint, AsyncCallback callback)
		{
			if(udpanysourcemulticastclient == null) throw new ArgumentNullException("udpanysourcemulticastclient");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return udpanysourcemulticastclient.BeginSendTo(buffer, 0, buffer.Length, remoteEndPoint, callback);
		}

	}
}
