//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewRowDividerDoubleClickEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewRowDividerDoubleClickEventHandler">DataGridViewRowDividerDoubleClickEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewRowDividerDoubleClickEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewrowdividerdoubleclickeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewRowDividerDoubleClickEventHandler datagridviewrowdividerdoubleclickeventhandler, Object sender, DataGridViewRowDividerDoubleClickEventArgs e, AsyncCallback callback)
		{
			if(datagridviewrowdividerdoubleclickeventhandler == null) throw new ArgumentNullException("datagridviewrowdividerdoubleclickeventhandler");

			return datagridviewrowdividerdoubleclickeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
