//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewRowCancelEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewRowCancelEventHandler">DataGridViewRowCancelEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewRowCancelEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewrowcanceleventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewRowCancelEventHandler datagridviewrowcanceleventhandler, Object sender, DataGridViewRowCancelEventArgs e, AsyncCallback callback)
		{
			if(datagridviewrowcanceleventhandler == null) throw new ArgumentNullException("datagridviewrowcanceleventhandler");

			return datagridviewrowcanceleventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
