#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net;

namespace PRI.ProductivityExtensions.DownloadProgressChangedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.DownloadProgressChangedEventHandler">DownloadProgressChangedEventHandler</seealso>
	/// </summary>
	public static partial class DownloadProgressChangedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// downloadprogresschangedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DownloadProgressChangedEventHandler downloadprogresschangedeventhandler, Object sender, DownloadProgressChangedEventArgs e, AsyncCallback callback)
		{
			if(downloadprogresschangedeventhandler == null) throw new ArgumentNullException("downloadprogresschangedeventhandler");

			return downloadprogresschangedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif