#if (NET40 || NET45)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Configuration;

namespace PRI.ProductivityExtensions.SettingChangingEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Configuration.SettingChangingEventHandler">SettingChangingEventHandler</seealso>
	/// </summary>
	public static partial class SettingChangingEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// settingchangingeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this SettingChangingEventHandler settingchangingeventhandler, Object sender, SettingChangingEventArgs e, AsyncCallback callback)
		{
			if(settingchangingeventhandler == null) throw new ArgumentNullException("settingchangingeventhandler");

			return settingchangingeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif