//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Navigation;

namespace PRI.ProductivityExtensions.FragmentNavigationEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Navigation.FragmentNavigationEventHandler">FragmentNavigationEventHandler</seealso>
	/// </summary>
	public static partial class FragmentNavigationEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// fragmentnavigationeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this FragmentNavigationEventHandler fragmentnavigationeventhandler, Object sender, FragmentNavigationEventArgs e, AsyncCallback callback)
		{
			if(fragmentnavigationeventhandler == null) throw new ArgumentNullException("fragmentnavigationeventhandler");

			return fragmentnavigationeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
