#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.NetworkInformation;

namespace PRI.ProductivityExtensions.NetworkAddressChangedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.NetworkInformation.NetworkAddressChangedEventHandler">NetworkAddressChangedEventHandler</seealso>
	/// </summary>
	public static partial class NetworkAddressChangedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// networkaddresschangedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this NetworkAddressChangedEventHandler networkaddresschangedeventhandler, Object sender, EventArgs e, AsyncCallback callback)
		{
			if(networkaddresschangedeventhandler == null) throw new ArgumentNullException("networkaddresschangedeventhandler");

			return networkaddresschangedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif