#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.NavigateEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.NavigateEventHandler">NavigateEventHandler</seealso>
	/// </summary>
	public static partial class NavigateEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// navigateeventhandler.BeginInvoke(sender, ne, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this NavigateEventHandler navigateeventhandler, Object sender, NavigateEventArgs ne, AsyncCallback callback)
		{
			if(navigateeventhandler == null) throw new ArgumentNullException("navigateeventhandler");

			return navigateeventhandler.BeginInvoke(sender, ne, callback, null);
		}

	}
}
#endif