//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Navigation;

namespace PRI.ProductivityExtensions.NavigatedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Navigation.NavigatedEventHandler">NavigatedEventHandler</seealso>
	/// </summary>
	public static partial class NavigatedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// navigatedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this NavigatedEventHandler navigatedeventhandler, Object sender, NavigationEventArgs e, AsyncCallback callback)
		{
			if(navigatedeventhandler == null) throw new ArgumentNullException("navigatedeventhandler");

			return navigatedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
