//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Navigation;

namespace PRI.ProductivityExtensions.NavigationFailedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Navigation.NavigationFailedEventHandler">NavigationFailedEventHandler</seealso>
	/// </summary>
	public static partial class NavigationFailedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// navigationfailedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this NavigationFailedEventHandler navigationfailedeventhandler, Object sender, NavigationFailedEventArgs e, AsyncCallback callback)
		{
			if(navigationfailedeventhandler == null) throw new ArgumentNullException("navigationfailedeventhandler");

			return navigationfailedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
