#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net;

namespace PRI.ProductivityExtensions.OpenReadCompletedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.OpenReadCompletedEventHandler">OpenReadCompletedEventHandler</seealso>
	/// </summary>
	public static partial class OpenReadCompletedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// openreadcompletedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this OpenReadCompletedEventHandler openreadcompletedeventhandler, Object sender, OpenReadCompletedEventArgs e, AsyncCallback callback)
		{
			if(openreadcompletedeventhandler == null) throw new ArgumentNullException("openreadcompletedeventhandler");

			return openreadcompletedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif