//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Net.Sockets;

namespace PRI.ProductivityExtensions.TcpListenerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Net.Sockets.TcpListener">TcpListener</seealso>
	/// </summary>
	public static partial class TcpListenerable
	{
#if (NET4_5 || NET4_0)
		/// <summary>
		/// Extends BeginAcceptSocket so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// tcplistener.BeginAcceptSocket(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginAcceptSocket(this TcpListener tcplistener, AsyncCallback callback)
		{
			if(tcplistener == null) throw new ArgumentNullException("tcplistener");

			return tcplistener.BeginAcceptSocket(callback, null);
		}

		/// <summary>
		/// Extends BeginAcceptTcpClient so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// tcplistener.BeginAcceptTcpClient(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginAcceptTcpClient(this TcpListener tcplistener, AsyncCallback callback)
		{
			if(tcplistener == null) throw new ArgumentNullException("tcplistener");

			return tcplistener.BeginAcceptTcpClient(callback, null);
		}
#endif
	}
}
