#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace PRI.ProductivityExtensions.ResolveEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ResolveEventHandler">ResolveEventHandler</seealso>
	/// </summary>
	public static partial class ResolveEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// resolveeventhandler.BeginInvoke(sender, args, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ResolveEventHandler resolveeventhandler, Object sender, ResolveEventArgs args, AsyncCallback callback)
		{
			if(resolveeventhandler == null) throw new ArgumentNullException("resolveeventhandler");

			return resolveeventhandler.BeginInvoke(sender, args, callback, null);
		}

	}
}
#endif