#if (NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Runtime.Remoting.Contexts;

namespace PRI.ProductivityExtensions.CrossContextDelegateExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Runtime.Remoting.Contexts.CrossContextDelegate">CrossContextDelegate</seealso>
	/// </summary>
	public static partial class CrossContextDelegateable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// crosscontextdelegate.BeginInvoke(callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this CrossContextDelegate crosscontextdelegate, AsyncCallback callback)
		{
			if(crosscontextdelegate == null) throw new ArgumentNullException("crosscontextdelegate");

			return crosscontextdelegate.BeginInvoke(callback, null);
		}

	}
}
#endif