//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel.Design;

namespace PRI.ProductivityExtensions.ComponentEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.ComponentModel.Design.ComponentEventHandler">ComponentEventHandler</seealso>
	/// </summary>
	public static partial class ComponentEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// componenteventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ComponentEventHandler componenteventhandler, Object sender, ComponentEventArgs e, AsyncCallback callback)
		{
			if(componenteventhandler == null) throw new ArgumentNullException("componenteventhandler");

			return componenteventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
