#if (NET4O || NET45 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.HelpEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.HelpEventHandler">HelpEventHandler</seealso>
	/// </summary>
	public static partial class HelpEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// helpeventhandler.BeginInvoke(sender, hlpevent, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this HelpEventHandler helpeventhandler, Object sender, HelpEventArgs hlpevent, AsyncCallback callback)
		{
			if(helpeventhandler == null) throw new ArgumentNullException("helpeventhandler");

			return helpeventhandler.BeginInvoke(sender, hlpevent, callback, null);
		}

	}
}
#endif