//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms.Layout;

namespace PRI.ProductivityExtensions.TableLayoutSettingsTypeConverterExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.Layout.TableLayoutSettingsTypeConverter">TableLayoutSettingsTypeConverter</seealso>
	/// </summary>
	public static partial class TableLayoutSettingsTypeConverterable
	{
		/// <summary>
		/// Extends ConvertTo so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// typeconverter.ConvertTo<int>(value);
		/// </example>
		/// </summary>
		public static T ConvertTo<T>(this TableLayoutSettingsTypeConverter typeconverter, Object value)
		{
			if(typeconverter == null) throw new ArgumentNullException("typeconverter");

			return (T)typeconverter.ConvertTo(value, typeof(T));
		}

		/// <summary>
		/// Extends ConvertTo so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// tablelayoutsettingstypeconverter.ConvertTo<int>(context, culture, value);
		/// </example>
		/// </summary>
		public static T ConvertTo<T>(this TableLayoutSettingsTypeConverter tablelayoutsettingstypeconverter, System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, Object value)
		{
			if(tablelayoutsettingstypeconverter == null) throw new ArgumentNullException("tablelayoutsettingstypeconverter");

			return (T)tablelayoutsettingstypeconverter.ConvertTo(context, culture, value, typeof(T));
		}

	}
}
