//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;

namespace PRI.ProductivityExtensions.ExceptionRoutedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.ExceptionRoutedEventHandler">ExceptionRoutedEventHandler</seealso>
	/// </summary>
	public static partial class ExceptionRoutedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// exceptionroutedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ExceptionRoutedEventHandler exceptionroutedeventhandler, Object sender, ExceptionRoutedEventArgs e, AsyncCallback callback)
		{
			if(exceptionroutedeventhandler == null) throw new ArgumentNullException("exceptionroutedeventhandler");

			return exceptionroutedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
