#if (NETSTANDARD2_0 || NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Xml.Serialization;

namespace PRI.ProductivityExtensions.XmlSchemasExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Xml.Serialization.XmlSchemas">XmlSchemas</seealso>
	/// </summary>
	public static partial class XmlSchemasable
	{
		/// <summary>
		/// Extends Find so that methods that return a specific type object given a Type parameter can be
		/// used as generic method and casting is not required.
		/// <example>
		/// xmlschemas.Find&lt;int&gt;(name);
		/// </example>
		/// </summary>
		public static T Find<T>(this XmlSchemas xmlschemas, System.Xml.XmlQualifiedName name)
		{
			if(xmlschemas == null) throw new ArgumentNullException("xmlschemas");

			return (T)xmlschemas.Find(name, typeof(T));
		}

	}
}
#endif