//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Media;

namespace PRI.ProductivityExtensions.LogReadyRoutedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Media.LogReadyRoutedEventHandler">LogReadyRoutedEventHandler</seealso>
	/// </summary>
	public static partial class LogReadyRoutedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// logreadyroutedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this LogReadyRoutedEventHandler logreadyroutedeventhandler, Object sender, LogReadyRoutedEventArgs e, AsyncCallback callback)
		{
			if(logreadyroutedeventhandler == null) throw new ArgumentNullException("logreadyroutedeventhandler");

			return logreadyroutedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
