//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.DataGridViewRowContextMenuStripNeededEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.DataGridViewRowContextMenuStripNeededEventHandler">DataGridViewRowContextMenuStripNeededEventHandler</seealso>
	/// </summary>
	public static partial class DataGridViewRowContextMenuStripNeededEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// datagridviewrowcontextmenustripneededeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this DataGridViewRowContextMenuStripNeededEventHandler datagridviewrowcontextmenustripneededeventhandler, Object sender, DataGridViewRowContextMenuStripNeededEventArgs e, AsyncCallback callback)
		{
			if(datagridviewrowcontextmenustripneededeventhandler == null) throw new ArgumentNullException("datagridviewrowcontextmenustripneededeventhandler");

			return datagridviewrowcontextmenustripneededeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
