//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Odbc;

namespace PRI.ProductivityExtensions.OdbcRowUpdatingEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.Odbc.OdbcRowUpdatingEventHandler">OdbcRowUpdatingEventHandler</seealso>
	/// </summary>
	public static partial class OdbcRowUpdatingEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// odbcrowupdatingeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this OdbcRowUpdatingEventHandler odbcrowupdatingeventhandler, Object sender, OdbcRowUpdatingEventArgs e, AsyncCallback callback)
		{
			if(odbcrowupdatingeventhandler == null) throw new ArgumentNullException("odbcrowupdatingeventhandler");

			return odbcrowupdatingeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
