//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows.Forms;

namespace PRI.ProductivityExtensions.ToolStripContentPanelRenderEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Windows.Forms.ToolStripContentPanelRenderEventHandler">ToolStripContentPanelRenderEventHandler</seealso>
	/// </summary>
	public static partial class ToolStripContentPanelRenderEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// toolstripcontentpanelrendereventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ToolStripContentPanelRenderEventHandler toolstripcontentpanelrendereventhandler, Object sender, ToolStripContentPanelRenderEventArgs e, AsyncCallback callback)
		{
			if(toolstripcontentpanelrendereventhandler == null) throw new ArgumentNullException("toolstripcontentpanelrendereventhandler");

			return toolstripcontentpanelrendereventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
