#if (NETSTANDARD2_0 || NET45 || NET40 || NET451 || NET452 || NET46 || NET461 || NET462)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Common;

namespace PRI.ProductivityExtensions.DbDataRecordExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Data.Common.DbDataRecord">DbDataRecord</seealso>
	/// </summary>
	public static partial class DbDataRecordable
	{
		/// <summary>
		/// Extends GetBytes so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// dbdatarecord.GetBytes(i, dataIndex, buffer);
		/// </example>
		/// </summary>
		public static Int64 GetBytes(this DbDataRecord dbdatarecord, Int32 i, Int64 dataIndex, Byte[] buffer)
		{
			if(dbdatarecord == null) throw new ArgumentNullException("dbdatarecord");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return dbdatarecord.GetBytes(i, dataIndex, buffer, 0, buffer.Length);
		}

		/// <summary>
		/// Extends GetChars so that buffer offset of 0 and call to Array.Length are not needed.
		/// <example>
		/// dbdatarecord.GetChars(i, dataIndex, buffer);
		/// </example>
		/// </summary>
		public static Int64 GetChars(this DbDataRecord dbdatarecord, Int32 i, Int64 dataIndex, Char[] buffer)
		{
			if(dbdatarecord == null) throw new ArgumentNullException("dbdatarecord");

			if(buffer == null) throw new ArgumentNullException("buffer");

			return dbdatarecord.GetChars(i, dataIndex, buffer, 0, buffer.Length);
		}

	}
}
#endif