#if (NET4_0 || NET4_5)
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Drawing.Design;

namespace PRI.ProductivityExtensions.ToolboxComponentsCreatedEventHandlerExtensions
{

	/// <summary>
	/// Class that contains extension methods that extend <seealso cref="System.Drawing.Design.ToolboxComponentsCreatedEventHandler">ToolboxComponentsCreatedEventHandler</seealso>
	/// </summary>
	public static partial class ToolboxComponentsCreatedEventHandlerable
	{
		/// <summary>
		/// Extends BeginInvoke so that when a state object is not needed, null does not need to be passed.
		/// <example>
		/// toolboxcomponentscreatedeventhandler.BeginInvoke(sender, e, callback);
		/// </example>
		/// </summary>
		public static IAsyncResult BeginInvoke(this ToolboxComponentsCreatedEventHandler toolboxcomponentscreatedeventhandler, Object sender, ToolboxComponentsCreatedEventArgs e, AsyncCallback callback)
		{
			if(toolboxcomponentscreatedeventhandler == null) throw new ArgumentNullException("toolboxcomponentscreatedeventhandler");

			return toolboxcomponentscreatedeventhandler.BeginInvoke(sender, e, callback, null);
		}

	}
}
#endif